<?php
namespace grozzzny\depends\mdbootstrap;

class MDBootstrapPluginAsset extends \yii\web\AssetBundle
{
    // Modules
    public $chart = false;
    public $enhancedModals = false;
    public $formsFree = false;
    public $jqueryEasing = false;
    public $scrollingNavbar = false;
    public $velocity = false;
    public $waves = false;
    public $wow = false;

    public $sourcePath = '@grozzzny/depends/mdbootstrap/src';
    public $js = [
        'js/mdb.min.js',
    ];
    public $depends = [
        'grozzzny\depends\bootstrap4\Bootstrap4Asset',
        'grozzzny\depends\bootstrap4\Bootstrap4PluginAsset',
        'grozzzny\depends\mdbootstrap\MDBootstrapAsset',
        'grozzzny\depends\popper\PopperAsset',
    ];

    public function init()
    {
        if ($this->chart) $this->js[] =  'js/modules/chart.js';
        if ($this->enhancedModals) $this->js[] =  'js/modules/enhanced-modals.js';
        if ($this->formsFree) $this->js[] =  'js/modules/forms-free.js';
        if ($this->jqueryEasing) $this->js[] =  'js/modules/jquery.easing.js';
        if ($this->scrollingNavbar) $this->js[] =  'js/modules/scrolling-navbar.js';
        if ($this->velocity) $this->js[] =  'js/modules/velocity.min.js';
        if ($this->waves) $this->js[] =  'js/modules/waves.js';
        if ($this->wow) $this->js[] =  'js/modules/wow.js';

        parent::init(); // TODO: Change the autogenerated stub
    }
}
