<?php
namespace grozzzny\depends\jquery_migrate;

use yii\web\View;

class JqueryMigrateAsset extends \yii\web\AssetBundle
{
    public $mute = true;
    public $sourcePath = '@grozzzny/depends/jquery_migrate';
    public $js = [
        'jquery-migrate-3.0.0.js',
    ];
    public $depends = [
        'yii\web\JqueryAsset',
    ];
    
    public function init()
    {
        if(!$this->mute) array_unshift($this->js, 'migrateMute.js');
        parent::init(); // TODO: Change the autogenerated stub
    }
}
