<?php
namespace grozzzny\depends\gmap;

use yii\web\View;

class GmapAsset extends \yii\web\AssetBundle
{
    public $sourcePath = '@grozzzny/depends/gmap';

    public $key = '';

    public $js = [
        'jquery.gmap.js',
    ];
    public $depends = [
        'yii\web\JqueryAsset',
    ];
    public $jsOptions = [
        'position' => View::POS_HEAD
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        array_unshift($this->js, 'https://maps.google.com/maps/api/js?key='.$this->key);
    }
}
